'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const {fingerprint,validateClaim,selectClaim,eligibilityCopy,compactClaim}=require('../resident_logic.js');
(async()=>{
 const rule={team_rule_id:'T',quoted_span:'A landlord must give a written notice before proceeding.',requirement:'Written notice is required.',status:'in_force',effective_date:'2026-01-01',coverage_conditions:'Residential',exemptions:null};
 const provenance={supporting_spans:[{id:'E1',text:'The exemption covers a resident owner with one extra renter.'}],authorized_companion_spans:[{id:'C1',text:'The date clause states January 1 of the following year.',source_doc_id:'P1'}]};
 const hash=await fingerprint(rule);
 const claim={team_rule_id:'T',rule_fingerprint:hash,claim_id:'C',scope:'rule_meaning',text:'The landlord must give written notice.',evidence:[{span_id:'rule-quote',text:rule.quoted_span}],extractor:{approved:true,model:'actual-model',request_id:'msg1'},reviewer:{approved:true,model:'actual-model',request_id:'msg2'}};
 assert.ok(validateClaim(claim,rule,provenance,hash));
 assert.equal(selectClaim([],rule,provenance,hash),null);
 assert.equal(selectClaim([{...claim,reviewer:{...claim.reviewer,approved:false}}],rule,provenance,hash),null);
 assert.equal(validateClaim({...claim,rule_fingerprint:'stale'},rule,provenance,hash),false);
 assert.equal(validateClaim(claim,rule,provenance,await fingerprint({...rule,exemptions:'New exemption'})),false);
 assert.equal(validateClaim({...claim,evidence:[{span_id:'rule-quote',text:'An invented quotation with no support.'}]},rule,provenance,hash),false);
 assert.equal(validateClaim({...claim,reviewer:{...claim.reviewer,request_id:'msg1'}},rule,provenance,hash),false);
 assert.equal(validateClaim({...claim,scope:'personal_entitlement'},rule,provenance,hash),false);
 assert.ok(validateClaim({...claim,evidence:[{span_id:'support:0',text:provenance.supporting_spans[0].text}]},rule,provenance,hash));
 assert.ok(validateClaim({...claim,evidence:[{span_id:'companion:0',text:provenance.authorized_companion_spans[0].text}]},rule,provenance,hash));
 assert.equal(validateClaim({...claim,evidence:[{span_id:'companion:1',text:provenance.authorized_companion_spans[0].text}]},rule,provenance,hash),false);
 assert.match(eligibilityCopy({result:'pending'}),/not a current protection/);
 assert.match(eligibilityCopy({result:'not_yet_effective'}),/not in effect/);
 assert.match(eligibilityCopy({result:'unknown',explanation:'Coverage compilation did not pass independent review.'}),/reliable legal/);
 assert.match(eligibilityCopy({result:'unknown',explanation:'Missing year built'}),/need more facts/);
 assert.equal(compactClaim({text:'word '.repeat(61)}).showInline,false);assert.equal(compactClaim({text:'word '.repeat(60)}).showInline,true);
 assert.match(compactClaim({text:'word '.repeat(61)}).explanation,/important conditions/);
 const app=fs.readFileSync(require('node:path').resolve(__dirname,'../app.js'),'utf8');
 const safe=app.slice(app.indexOf('function safeUrl('),app.indexOf('async function fetchJson('));
 const ctx={URL,window:{location:{href:'https://example.org/ui/'}}};vm.createContext(ctx);vm.runInContext(safe,ctx);
 assert.equal(ctx.safeUrl('javascript:alert(1)'),null);assert.equal(ctx.safeUrl('data:text/html,<script>alert(1)</script>'),null);
 assert.equal(ctx.safeUrl('https://example.org/source'),'https://example.org/source');
 assert.match(app,/node\.textContent = String\(text\)/);assert.doesNotMatch(app,/innerHTML\s*=/);
 assert.match(app,/ResidentLogic\.eligibilityCopy\(entry\)/);
 console.log('PASS: 24 evidence-gate, stale, unsupported, independent review, status, qualification and XSS assertions.');
})().catch(e=>{console.error(e);process.exit(1)});
